def show_sentence_maintenance_help():
    """Display comprehensive help for Sentence Maintenance"""
    
    content_lines = [
        f"{Colors.BRIGHT_CYAN}OVERVIEW{Colors.RESET}",
        f"{Colors.DIM}{'─' * 80}{Colors.RESET}",
        "Sentence Maintenance allows you to browse all projects, headings, and sentences",
        "in your database. You can copy sentences and headings, and delete headings.",
        "",
        f"{Colors.BRIGHT_CYAN}NAVIGATION{Colors.RESET}",
        f"{Colors.DIM}{'─' * 80}{Colors.RESET}",
        f"  {Colors.BRIGHT_YELLOW}@x{Colors.RESET}           Toggle collapse/expand for project x (a, b, c, etc.)",
        "                 Collapsed projects show only the project name",
        "                 Expanded projects show all headings, subheadings, and sentences",
        "",
        f"  {Colors.BRIGHT_YELLOW}h{Colors.RESET}            Previous page",
        f"  {Colors.BRIGHT_YELLOW}l{Colors.RESET}            Next page",
        "",
        f"{Colors.BRIGHT_CYAN}UNDERSTANDING IDS{Colors.RESET}",
        f"{Colors.DIM}{'─' * 80}{Colors.RESET}",
        "Each element has an ID shown in bright yellow:",
        "",
        f"  {Colors.BRIGHT_BLUE}[a]{Colors.RESET} My Project {Colors.DIM}(proj_id:{Colors.BRIGHT_YELLOW}1{Colors.DIM}){Colors.RESET}",
        f"    {Colors.CYAN}\u2022 Introduction{Colors.RESET} {Colors.DIM}(mc_id:{Colors.BRIGHT_YELLOW}5{Colors.DIM}){Colors.RESET}",
        f"      {Colors.BRIGHT_BLACK}\u2192 Background{Colors.RESET} {Colors.DIM}(sc_id:{Colors.BRIGHT_YELLOW}12{Colors.DIM}){Colors.RESET}",
        f"        {Colors.BRIGHT_GREEN}[47]{Colors.RESET} This is the first sentence.",
        f"        {Colors.BRIGHT_GREEN}[48]{Colors.RESET} This is the second sentence.",
        "",
        "• proj_id = Project ID",
        "• mc_id = Major Category (Heading) ID",
        "• sc_id = Subcategory (Subheading) ID",
        "• [##] = Sentence ID",
        "",
        f"{Colors.BRIGHT_CYAN}SENTENCE COMMANDS{Colors.RESET}",
        f"{Colors.DIM}{'─' * 80}{Colors.RESET}",
        f"  {Colors.BRIGHT_YELLOW}cs <sentence_id> <sc_id>{Colors.RESET}",
        "  Copy sentence to a subheading (any project)",
        "  The sentence remains in its original location",
        "  Example:",
        f"    {Colors.DIM}cs 48 20{Colors.RESET}     Copy sentence 48 to subheading sc_id:20",
        "",
        f"{Colors.BRIGHT_CYAN}HEADING COMMANDS{Colors.RESET}",
        f"{Colors.DIM}{'─' * 80}{Colors.RESET}",
        f"  {Colors.BRIGHT_YELLOW}ch <mc_id> <before_mc_id>{Colors.RESET}",
        "  Copy heading before another heading (same project)",
        "  Copies all subheadings and sentences",
        "  Example:",
        f"    {Colors.DIM}ch 5 3{Colors.RESET}      Copy heading mc_id:5 before mc_id:3",
        "",
        f"  {Colors.BRIGHT_YELLOW}cp <mc_id> <proj_id>{Colors.RESET}",
        "  Copy heading to another project",
        "  Copies all subheadings and sentences to end of target project",
        "  Example:",
        f"    {Colors.DIM}cp 5 2{Colors.RESET}      Copy heading mc_id:5 to project proj_id:2",
        "",
        f"  {Colors.BRIGHT_YELLOW}dh <mc_id>{Colors.RESET}",
        "  Delete heading (and all its subheadings and sentences)",
        "  Example:",
        f"    {Colors.DIM}dh 5{Colors.RESET}        Delete heading mc_id:5",
        "",
        f"{Colors.BRIGHT_CYAN}TYPICAL WORKFLOWS{Colors.RESET}",
        f"{Colors.DIM}{'─' * 80}{Colors.RESET}",
        "Copy sentence to another location:",
        "  1. Expand projects: @a, @b",
        "  2. Note sentence ID [###] and target sc_id",
        "  3. Use: cs 48 20",
        "",
        "Move sentence (copy then delete):",
        "  1. Copy: cs 48 20",
        "  2. Delete original from outline editor: d 48",
        "",
        "Reorder heading within project:",
        "  1. Copy before target: ch 5 3",
        "  2. Delete original: dh 5",
        "",
        "Move heading to another project:",
        "  1. Copy to project: cp 5 2",
        "  2. Delete original: dh 5",
        "",
        f"{Colors.BRIGHT_CYAN}TIPS{Colors.RESET}",
        f"{Colors.DIM}{'─' * 80}{Colors.RESET}",
        "• IDs are shown in bright yellow: proj_id, mc_id, sc_id, sentence [id]",
        "• Copy operations are safer than move - you can delete after verifying",
        "• Collapse projects you're not working with to reduce clutter",
        "• Use paging (h/l) if you have many projects",
        "• Delete heading (dh) removes all subheadings and sentences - be careful!",
        "",
        f"{Colors.BRIGHT_CYAN}OTHER COMMANDS{Colors.RESET}",
        f"{Colors.DIM}{'─' * 80}{Colors.RESET}",
        f"  {Colors.BRIGHT_YELLOW}q{Colors.RESET}            Quit and return to main menu",
        f"  {Colors.BRIGHT_YELLOW}?{Colors.RESET}            Show this help screen",
    ]
    
    show_paged_help(content_lines, "SENTENCE MAINTENANCE - HELP")
